typography_spectrum: 0.5714696499053389
color:
  brandColors:
    - '#000000'
    - '#212121'
    - '#676767'
    - '#a0a0a0'
    - '#cbcbcb'
  brandStrength: 0.612768174149096
  lightness: 0.2642074953764677
  saturation: 0.8015512903220952
  rhythmicContrast: 0.914414151571691
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.89247
analytics:
  google: null
  facebook: null
  twitter: null
name: Sundae
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Sundae Philadelphia
description: 'if you''re not here to dance, go home'
purpose: []
