name: Sundae
favicon: null
layout_spectrum: 0.89247
typography_spectrum: 0.5714696499053389
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#212121'
    - '#676767'
    - '#a0a0a0'
    - '#cbcbcb'
  brandStrength: 0.612768174149096
  lightness: 0.2642074953764677
  saturation: 0.8015512903220952
  rhythmicContrast: 0.914414151571691
purpose: []
